id = "protobuf-ls"
name = "Protobuf LS"
description = """
Protobuf language server support.
Based on https://github.com/lasorda/protobuf-language-server.
This extension will NOT install the language srver automatically but will require you to install it manually.
"""
version = "0.1.0"
schema_version = 1
authors = ["prskr <peter.kurfer@gmail.com>"]
repository = "https://github.com/prskr/zed-protobuf"

[language_servers.protobuf-ls]
name = "Protobuf Language Server"
language = "protobuf-ls"
languages = ["proto"]
